version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data    

  backend:
    build:
      context: ./backend
    container_name: backend_dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env.docker
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
    container_name: frontend_dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.docker
    command: npm run dev

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
  redis_data: